spring:
  application:
    name: knowyou-ai-agent
  profiles:
    active: local
  ai:
    dashscope:
      api-key: 'sk-b793b70b9b4a428fa089f82368669fb1'
      chat:
        options:
          model: qwen-plus
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
  - group: 'default'
    paths-to-match: '/**'
    packages-to-scan: com.knowyou.knowyouaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
model:
  config:
    api-key: 'sk-b793b70b9b4a428fa089f82368669fb1'
# 修改日志级别，查看 Spring AI 更多调用细节
logging:
  level:
    org.springframework.ai: debug